server:
  servlet:
    context-path: /phaedra/metadata-service
  port: 3002

spring:
  application:
    name: phaedra-metadata-service
  liquibase:
    enabled: false
  jackson:
    serialization:
      indent_output: true
  cloud:
    kubernetes:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

logging:
  file:
    name: /var/log/metadataservice.log
